[변경사항] 전체적인 디자인 제거 및 새로운 로직을 구성함.
seojin1176/To-Do-List-Project pull request #2
Opened 2024-07-18 03:49 UTC by seojin1176

[기능] 할 일 추가 버튼을 눌렀을 때 모달창이 열리는 것.
[기능] 모달창을 열고 난 후 추가 버튼을 눌렀을 때 제목 입력 밑에 있는 인풋의 값을 공백 여부를 판단하여 모달창이 닫힘의 여부 결정. 
[기능] 닫기 버튼 누르면 값이 있든 말든 그냥 닫힘.
[추가된 것] 새로운 라이브러리 사용 recoil, recoil-persist 사용함.
[추가된 파일] atoms.js에 state값에 담길 초기 값과 기본 값, 새로고침이나 페이지를 닫아도 유지되는 코드가 있음. 
[추가된 파일] reportWebVials.js 사실 어떤 파일인지 정확히 모르지만 새로 설치한 라이브러리 사용을 위한 파일을 만듦. 
[수정된 것] index.js에 recoil을 사용하기 위한 코드 추가

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/App.jsx
> +import MModal from "./MModal";
p2. 자바스크립트 기반 언어는 코드를 위에서 아래로 한줄 씩 읽기때문에 import 순서가 중요합니다.
보통은 아래 순서로 import를 합니다.
추가로 빈줄을 추가해주면 가독성을 높일 수 있습니다!

1. 외부 라이브러리 (react, recoil 등)
2. 컴포넌트 또는 로직들
3. 스타일

예시 )
import React from "react";
import { useRecoilState } from "recoil";

import MModal from "./MModal";
import { modalState } from "./atoms";

import "../src/App.css";

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/App.jsx
> +  const [modal, setModal] = useRecoilState(modalState);
p4. modal이라는 이름은 의미가 모호한 것 같아요!
이 상태가 정확히 어떤 역할을 하는지를 담고 있으면 좋아요!

예시) [addTodoModalVisible, setAddTodoModalVisible]

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/App.jsx
> +  };
p2. 동일한 함수가 2개 있습니다! 삭제해주세요

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/App.jsx
> +      <MModal isOpen={modal} closmodal={closModal} closeModal={closeModal} />
p2. closemodal이나 closeModal 둘중 하나만 사용해주세요!

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
p2. MModal은 어떤 의미인지 모르겠네요. 수정부탁드려요!

예시 ) AddTodoModal.jsx

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +  const [inputValue, setinputvalue] = useRecoilState(inputValuesState);
p2. inputValue 보단 todoTitle 정도가 좋을 것 같습니다!

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +  const [comentValue, setcomentValue] = useRecoilState(comentValuesState);
p4. 설명은 보통 description이라는 키워드를 많이 써요!

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +  const [inputValue, setinputvalue] = useRecoilState(inputValuesState);
그리고 제목과 설명에는 recoil을 적용할 필요가 있는지 생각해보면 좋을 것 같아요!
recoil은 전역 변수 상태 관리로 여러 컴포넌트에서 공통된 값을 사용할 때 사용합니다

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +  const handleinputvlaue = () => {
p4. 해당 함수는 할일을 등록할 때 사용될 것은데 보통은 아래처럼 많이 씁니다.
함수명을 작명하는 팁은 해당 함수가 어떤 동작을 했을 때 실행된다(onClick, onChange) 보다는 어떤 역할을 하고 있는지로 적는게 좋아요!
다른 개발자들이 함수명만 보고 '아 이함수는 이런 역할을 하는 함수구나!' 라는 생각이 들게 하는게 베스트입니다.

- addTodo

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +    const modalInput = document.querySelector(".modalInput");
p3. document.querySelector가 아닌 위의 inputvlaue 상태를 사용하는건 어떨까요?
혹시 제가 모르는 이슈가 있나요?

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +    }
p2. early return을 사용하면 가독성과 속도를 개선할 수 있습니다!
if/else는 첫번째 조건이 맞아도 나머지 조건들을 한번씩 실행하기 때문에 속도 이슈가 발생합니다.

예시)
if (modalInput.value === "") {
  alert("값을 입력해주세요.");
  return;
}

closeModal();

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/MModal.jsx
> +  const modalContent = (
모달의 내용을 변수로 분리하니까 가독성이 좋아지네요! 👍

2024-07-18 04:45 UTC, AGLOP-1354 commented on src/index.js
> +reportWebVitals();
이 코드를 다시 추가한 이유가 있나요?

2024-07-18 05:03 UTC, seojin1176 commented on src/index.js
> +reportWebVitals();
실수인 것 같습니다..!

2024-07-18 05:05 UTC, seojin1176 commented on src/MModal.jsx
Modal은 리액트 안에서 Modal창으로 쓰이고 있어서 무슨 이름으로 고민하다가 결국 생각이 안나서 MModal로 했습니다 ㅜㅜ

2024-07-18 05:06 UTC, seojin1176 commented on src/App.jsx
> +import MModal from "./MModal";
넵 수정하겠습니다!

2024-07-18 05:07 UTC, seojin1176 commented on src/App.jsx
> +  };
넵! 수정하겠습니다

2024-07-18 05:10 UTC, seojin1176 commented on src/MModal.jsx
> +    const modalInput = document.querySelector(".modalInput");
앗 inputValue사용하는걸 생각하지 못했습니다..!

2024-07-18 05:10 UTC, seojin1176 commented on src/MModal.jsx
> +    }
넵 수정하겠습니다!

2024-07-18 05:16 UTC, seojin1176 commented on src/MModal.jsx
> +    const modalInput = document.querySelector(".modalInput");
방금 수정을 했을 때에 이유는 모르겠지만 inputValue.value를 하였을 때 제대로 작동하지 않아서 다시 document.querySelector을 다시 사용했습니다..!

2024-07-18 05:19 UTC, seojin1176 commented on src/App.jsx
> +  const [modal, setModal] = useRecoilState(modalState);
넵 참고하겠습니다!

2024-07-18 05:20 UTC, seojin1176 commented on src/App.jsx
> +      <MModal isOpen={modal} closmodal={closModal} closeModal={closeModal} />
수정했습니다!

2024-07-18 05:45 UTC, seojin1176 commented on src/MModal.jsx
> +  const [inputValue, setinputvalue] = useRecoilState(inputValuesState);
넵!! 알겠습니다!

2024-07-18 06:48 UTC, AGLOP-1354 requested changes

2024-07-18 06:48 UTC, AGLOP-1354 commented on src/App.jsx
> +  const [modalvisible, setmodalvisible] = useRecoilState(modalState);
p1. 단어 구분은 camelCase로 해주세요!

modalVisivble, setModalVisible

2024-07-18 06:48 UTC, AGLOP-1354 commented on src/App.jsx
> +  const [modalvisible, setmodalvisible] = useRecoilState(modalState);
아직 변수만 보고 어떤의미인지 파악하기 어렵습니다! 앞에 어떤 모달인지를 나타내는 워딩도 추가해주세요!

2024-07-18 06:48 UTC, AGLOP-1354 commented on src/index.js
>  reportWebVitals();
reportWebVitals도 제거해도 될 것 같습니다!

2024-07-19 01:15 UTC, seojin1176 commented on src/index.js
>  reportWebVitals();
넵! 알겠습니다

2024-07-19 01:15 UTC, seojin1176 commented on src/App.jsx
> +  const [modalvisible, setmodalvisible] = useRecoilState(modalState);
넵! 확인했습니다!

2024-07-19 01:27 UTC, seojin1176 commented on src/index.js
>  reportWebVitals();
수정 후 push하였습니다!

2024-07-19 07:52 UTC, AGLOP-1354 commented on src/TodoModal.jsx
> +  const [TodoTitle, setTodoTitle] = useRecoilState(inputValuesState);
p1. 변수명의 첫글자는 소문자로 해주세요!

2024-07-19 07:52 UTC, AGLOP-1354 commented on src/TodoModal.jsx
> +    const modalInput = document.querySelector(".modalInput");
todoTitle을 사용할 수 없는 이유는 inputValuesState의 기본값이 문자열이기 때문에 그렇습니다
기본 값을 수정해주세요!

2024-07-19 07:52 UTC, AGLOP-1354 commented on src/TodoModal.jsx
> +    const modalInput = document.querySelector(".modalInput");
inputValuesState도 todoTitleState 이런식으로 수정해주세요

2024-07-20 09:19 UTC, AGLOP-1354 approved these changes

2024-07-21 05:02 UTC, merged